<a href="https://colab.research.google.com/github/Klark-cyber/ai_foundation/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install numpy


In [ ]:
import numpy as np
arr = np.array([1,2,3,4])
print("numpy array:", arr)
arr.shape


numpy array: [1 2 3 4]


(4,)

In [ ]:
arr2 = np.array([[1,2,3,4], [5,6,7,8]])
print("numpy array:", arr2)
arr2.shape

numpy array: [[1 2 3 4]
 [5 6 7 8]]


(2, 4)

In [ ]:
# dtype bu method array typini aniqlab beradi
arr3 = np.array([1,2,3,4])
arr.dtype

dtype('int64')

In [ ]:
# reshape() bu arrayni kerakli shapega moslab teng taqsimlab beradigan method.
arr4 = np.array([1,2,3,4,5,6])
arr5= arr4.reshape(2,3)
print(arr5)

[[1 2 3]
 [4 5 6]]


In [ ]:
# astype - arrayni typini ozgartiradi.
arr6 = np.array([1,2,3,4,5,6])
arr7= arr4.astype(float) #array typi aslida integer edi endi u float
print("array type is", arr7)


array type is [1. 2. 3. 4. 5. 6.]


In [ ]:
# np.zeros() , np.ones() test uchun 0 dan yoki 1 dan iborat array hosil qilish uchun ishlatiladi
z=np.zeros((2,3))
o=np.ones((2,3))
print("zeros:", z)
print("ones:", o)

zeros: [[0. 0. 0.]
 [0. 0. 0.]]
ones: [[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# ndim bu matrisani necha olchamli (D) ekanligini aniqlab beradi.
a = np.array([[1,2,3],[4,5,6]])
print("ndim:", a.ndim)

ndim: 2


In [8]:
# arange(x,y) bu x va y-1 oraliqda yangi array hosil qiladi
import numpy as np
arr7 = np.arange(1, 6)
print(arr7)

[1 2 3 4 5]


In [11]:
# min(), max(), sum(), mean()
a = np.arange(1, 4)
print(a.min())
print(a.max())
print(a.sum())
print(a.mean()) #array yigindisining ortachasini topish

1
3
6
2.0


In [14]:
# flatten 2d,3d ... dan 1d olchamli errayga otkazadi
a = np.array([[1,2,3,4], [5,6,7,8]])
print(a.flatten())

[1 2 3 4 5 6 7 8]


In [16]:
# transpose() arrayni 1 elementlarini alohida 2 elementlarini alohida array sifatida hosil qiladi
a = np.array([[1,2,3,4], [5,6,7,8]])
print(a.T)

[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [17]:
# dot() array elementlarini kopaytiradi.
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])
C = np.dot(A, B) # [(1*5)+(2*7)=19, (1*6)+(2*8)=22], [(3*5)+(4+7)=43, (3*6)+(4*8)=50]

print(C)

[[19 22]
 [43 50]]


In [20]:
# random.rand(x,y) bu method 0.0 va 1.0 oraliqdagi random x qator va y ustun boyicha matritsa hosil qilib beradi
A = np.random.rand(2,3)
print(A)

[[0.74948726 0.03947073 0.5424283 ]
 [0.72616951 0.18178264 0.17672478]]
